In [7]:
import pandas as pd

In [8]:
df = pd.read_csv(
    "medical_store_dataset.csv"
)

In [9]:
df.head()

,Invoice_ID,Date,Customer_ID,Age_Group,Gender,Medicine_Name,Category,Manufacturer,Quantity,Unit_Price,Discount,Total_Sale,Stock_Available,Expiry_Date,Payment_Mode,Store_Location
0,INV00001,2026-05-06,CUST0229,Child,Male,Azithromycin,Antibiotic,Torrent,1,399,10,359.1,64,2027-08-28,UPI,Pune
1,INV00002,2026-09-16,CUST0617,Child,Male,Paracetamol,Painkiller,Torrent,2,131,5,248.9,234,2026-08-14,UPI,Nashik
2,INV00003,2026-12-24,CUST0433,Adult,Female,Cetirizine,Antihistamine,Cipla,1,408,5,387.6,130,2026-12-11,Cash,Pune
3,INV00004,2026-11-06,CUST0271,Child,Female,Pantoprazole,Gastro,Torrent,2,203,10,365.4,83,2027-01-23,Cash,Nashik
4,INV00005,2026-10-23,CUST0197,Senior,Male,Cetirizine,Antihistamine,Sun Pharma,10,473,10,4257.0,358,2026-08-22,UPI,Pune

In [9]:
df.shape

(5000, 16)

In [10]:
df.columns.tolist()

['Invoice_ID',
 'Date',
 'Customer_ID',
 'Age_Group',
 'Gender',
 'Medicine_Name',
 'Category',
 'Manufacturer',
 'Quantity',
 'Unit_Price',
 'Discount',
 'Total_Sale',
 'Stock_Available',
 'Expiry_Date',
 'Payment_Mode',
 'Store_Location']

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Invoice_ID       5000 non-null   str
 1   Date             5000 non-null   str
 2   Customer_ID      5000 non-null   str
 3   Age_Group        5000 non-null   str
 4   Gender           5000 non-null   str
 5   Medicine_Name    5000 non-null   str
 6   Category         5000 non-null   str
 7   Manufacturer     5000 non-null   str
 8   Quantity         5000 non-null   int64
 9   Unit_Price       5000 non-null   int64
 10  Discount         5000 non-null   int64
 11  Total_Sale       5000 non-null   float64
 12  Stock_Available  5000 non-null   int64
 13  Expiry_Date      5000 non-null   str
 14  Payment_Mode     5000 non-null   str
 15  Store_Location   5000 non-null   str
dtypes: float64(1), int64(4), str(11)
memory usage: 625.1 KB

In [12]:
df.describe()

          Quantity   Unit_Price     Discount   Total_Sale  Stock_Available
count  5000.000000  5000.000000  5000.000000  5000.000000      5000.000000
mean      5.435600   262.161800     7.503000  1312.886710       257.466000
std       2.845395   138.815215     5.644144  1044.128186       137.374475
min       1.000000    20.000000     0.000000    17.000000        20.000000
25%       3.000000   142.000000     0.000000   445.000000       139.000000
50%       5.000000   263.000000     5.000000  1026.000000       254.000000
75%       8.000000   382.000000    15.000000  1953.675000       375.000000
max      10.000000   500.000000    15.000000  4980.000000       500.000000

In [13]:
df.isnull().sum()

Invoice_ID         0
Date               0
Customer_ID        0
Age_Group          0
Gender             0
Medicine_Name      0
Category           0
Manufacturer       0
Quantity           0
Unit_Price         0
Discount           0
Total_Sale         0
Stock_Available    0
Expiry_Date        0
Payment_Mode       0
Store_Location     0
dtype: int64

In [14]:
df['Medicine_Name']

0       Azithromycin
1        Paracetamol
2         Cetirizine
3       Pantoprazole
4         Cetirizine
            ...
4995       Metformin
4996     Amoxicillin
4997      Cetirizine
4998     Paracetamol
4999       Vitamin C
Name: Medicine_Name, Length: 5000, dtype: str

In [15]:
df[['Medicine_Name', 'Category']]

     Medicine_Name       Category
0     Azithromycin     Antibiotic
1      Paracetamol     Painkiller
2       Cetirizine  Antihistamine
3     Pantoprazole         Gastro
4       Cetirizine  Antihistamine
...            ...            ...
4995     Metformin       Diabetes
4996   Amoxicillin     Antibiotic
4997    Cetirizine  Antihistamine
4998   Paracetamol     Painkiller
4999     Vitamin C        Vitamin

[5000 rows x 2 columns]

In [16]:
df.loc[0]

Invoice_ID             INV00001
Date                   5/6/2026
Customer_ID            CUST0229
Age_Group                 Child
Gender                     Male
Medicine_Name      Azithromycin
Category             Antibiotic
Manufacturer            Torrent
Quantity                      1
Unit_Price                  399
Discount                     10
Total_Sale                359.1
Stock_Available              64
Expiry_Date           8/28/2027
Payment_Mode                UPI
Store_Location             Pune
Name: 0, dtype: object

In [17]:
df.iloc[0:10]

,Invoice_ID,Date,Customer_ID,Age_Group,Gender,Medicine_Name,Category,Manufacturer,Quantity,Unit_Price,Discount,Total_Sale,Stock_Available,Expiry_Date,Payment_Mode,Store_Location
0,INV00001,5/6/2026,CUST0229,Child,Male,Azithromycin,Antibiotic,Torrent,1,399,10,359.1,64,8/28/2027,UPI,Pune
1,INV00002,9/16/2026,CUST0617,Child,Male,Paracetamol,Painkiller,Torrent,2,131,5,248.9,234,8/14/2026,UPI,Nashik
2,INV00003,12/24/2026,CUST0433,Adult,Female,Cetirizine,Antihistamine,Cipla,1,408,5,387.6,130,12/11/2026,Cash,Pune
3,INV00004,11/6/2026,CUST0271,Child,Female,Pantoprazole,Gastro,Torrent,2,203,10,365.4,83,1/23/2027,Cash,Nashik
4,INV00005,10/23/2026,CUST0197,Senior,Male,Cetirizine,Antihistamine,Sun Pharma,10,473,10,4257.0,358,8/22/2026,UPI,Pune
5,INV00006,8/21/2026,CUST0651,Adult,Male,Vitamin C,Vitamin,Dr Reddy's,2,214,10,385.2,201,8/3/2026,Card,Mumbai
6,INV00007,10/1/2026,CUST0747,Child,Male,Azithromycin,Antibiotic,Lupin,10,345,5,3277.5,214,10/4/2026,Card,Nashik
7,INV00008,1/29/2026,CUST0235,Child,Female,Amlodipine,Cardiac,Lupin,4,370,10,1332.0,157,3/9/2026,Cash,Nashik
8,INV00009,7/22/2026,CUST0906,Senior,Female,Ibuprofen,Painkiller,Cipla,4,355,15,1207.0,155,5/23/2026,Cash,Nashik
9,INV00010,10/26/2026,CUST0409,Adult,Male,Amlodipine,Cardiac,Cipla,9,154,15,1178.1,280,5/21/2027,Cash,Pune

In [18]:
df['Category'].value_counts()

Category
Painkiller       1013
Antibiotic        991
Gastro            534
Diabetes          518
Antihistamine     507
Supplement        496
Cardiac           488
Vitamin           453
Name: count, dtype: int64

In [19]:
df['Total_Sale'].sum()

np.float64(6564433.55)

In [20]:
df['Total_Sale'].mean()

np.float64(1312.88671)

In [21]:
category_sales = df.groupby('Category')['Total_Sale'].sum().sort_values(ascending=False)
category_sales

Category
Antibiotic       1334967.05
Painkiller       1309831.10
Diabetes          706396.30
Gastro            682666.35
Antihistamine     661073.55
Cardiac           649264.95
Supplement        635178.45
Vitamin           585055.80
Name: Total_Sale, dtype: float64

In [22]:
top_medicines = df.groupby('Medicine_Name')['Total_Sale'].sum().sort_values(ascending=False).head(10)
top_medicines

Medicine_Name
Azithromycin    717546.05
Metformin       706396.30
Pantoprazole    682666.35
Ibuprofen       662426.50
Cetirizine      661073.55
Amlodipine      649264.95
Paracetamol     647404.60
ORS             635178.45
Amoxicillin     617421.00
Vitamin C       585055.80
Name: Total_Sale, dtype: float64

In [23]:
gender_sales = df.groupby('Gender')['Total_Sale'].sum()
gender_sales

Gender
Female    3240002.90
Male      3324430.65
Name: Total_Sale, dtype: float64

In [24]:
age_sales = df.groupby('Age_Group')['Total_Sale'].sum().sort_values(ascending=False)
age_sales

Age_Group
Adult     2311009.90
Senior    2167679.30
Child     2085744.35
Name: Total_Sale, dtype: float64

In [25]:
df['Date'] = pd.to_datetime(df['Date'])

In [26]:
monthly_sales = df.groupby(df['Date'].dt.to_period('M'))['Total_Sale'].sum()
monthly_sales

Date
2026-01    534768.30
2026-02    493955.95
2026-03    497053.15
2026-04    573720.90
2026-05    524930.05
2026-06    561315.80
2026-07    488579.95
2026-08    625688.80
2026-09    554126.05
2026-10    583606.20
2026-11    523091.15
2026-12    603597.25
Freq: M, Name: Total_Sale, dtype: float64

In [27]:
df['Expiry_Date'] = pd.to_datetime(df['Expiry_Date'])

In [28]:
expiring = df[
    df['Expiry_Date'] <= pd.Timestamp.today() + pd.DateOffset(months=6)
]

expiring[['Medicine_Name', 'Expiry_Date']].head(20)

   Medicine_Name Expiry_Date
1    Paracetamol  2026-08-14
2     Cetirizine  2026-12-11
4     Cetirizine  2026-08-22
5      Vitamin C  2026-08-03
6   Azithromycin  2026-10-04
7     Amlodipine  2026-03-09
8      Ibuprofen  2026-05-23
11    Cetirizine  2026-10-28
16     Vitamin C  2026-08-19
17   Paracetamol  2026-03-11
19  Pantoprazole  2026-02-25
20  Azithromycin  2026-05-24
22     Vitamin C  2026-01-03
24     Ibuprofen  2026-03-24
25           ORS  2026-02-10
27    Cetirizine  2026-08-07
29           ORS  2026-04-20
30   Amoxicillin  2026-09-15
33   Amoxicillin  2026-09-13
34     Ibuprofen  2026-07-01

In [29]:
low_stock = df[['Medicine_Name', 'Stock_Available']].sort_values('Stock_Available').head(10)
low_stock

     Medicine_Name  Stock_Available
1804           ORS               20
292   Pantoprazole               20
3907   Amoxicillin               20
1830    Cetirizine               20
762    Amoxicillin               20
2456     Ibuprofen               20
3384     Vitamin C               20
4319   Paracetamol               20
1484   Paracetamol               21
2289    Amlodipine               21

In [30]:
payment_sales = df.groupby('Payment_Mode')['Total_Sale'].sum().sort_values(ascending=False)
payment_sales

Payment_Mode
Card    2222700.70
UPI     2179271.90
Cash    2162460.95
Name: Total_Sale, dtype: float64

In [34]:
location_sales = df.groupby('Store_Location')['Total_Sale'].sum().sort_values(ascending=False)
location_sales

Store_Location
Pune      2200392.20
Nashik    2186916.20
Mumbai    2177125.15
Name: Total_Sale, dtype: float64

In [35]:
!pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in C:\Users\Rutuja\AppData\Roaming\Python\Python314\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\Users\Rutuja\AppData\Roaming\Python\Python314\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\Rutuja\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Rutuja\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)

In [43]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("Tanu@1107")   # IMPORTANT FIX
host = "localhost"
port = "5432"
database = "medical"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL
table_name = "medical_store"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'medical_store' in database 'medical'.